2018-06-14 16:20:24,788 - wechat_app - ERROR - An exception happened, details: 'Query' object has no attribute 'skip'
2018-06-14 16:20:35,821 - wechat_app - ERROR - An exception happened, details: 'Query' object has no attribute 'skip'
2018-06-14 16:21:09,316 - wechat_app - ERROR - An exception happened, details: 'Query' object has no attribute 'skip'
2018-06-14 16:26:18,614 - wechat_app - ERROR - An exception happened, details: an integer is required
2018-06-14 16:28:35,770 - wechat_app - ERROR - An exception happened, details: Query.order_by() being called on a Query which already has LIMIT or OFFSET applied. To modify the row-limited results of a  Query, call from_self() first.  Otherwise, call order_by() before limit() or offset() are applied.
2018-06-14 16:29:18,992 - wechat_app - ERROR - An exception happened, details: an integer is required
2018-06-14 16:29:35,678 - wechat_app - ERROR - An exception happened, details: an integer is required
2018-06-14 16:30:19,887 - wechat_app - ERROR - An exception happened, details: an integer is required
2018-06-14 16:33:12,755 - wechat_app - ERROR - An exception happened, details: an integer is required
2018-06-14 16:51:14,515 - wechat_app - ERROR - An exception happened, details: an integer is required
2018-06-14 16:51:35,483 - wechat_app - ERROR - An exception happened, details: an integer is required
2018-06-14 16:56:54,135 - wechat_app - ERROR - An exception happened, details: (_mysql_exceptions.ProgrammingError) (1146, "Table 'wechat_app.info' doesn't exist")
2018-06-14 17:01:25,767 - wechat_app - ERROR - An exception happened, details: (_mysql_exceptions.ProgrammingError) (1146, "Table 'wechat_app.info' doesn't exist")
2018-06-14 17:25:26,029 - wechat_app - ERROR - An exception happened, details: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'my_user.gener' in 'field list'")
2018-06-14 17:26:28,854 - wechat_app - ERROR - An exception happened, details: 'result' object has no attribute 'id'
2018-06-14 17:28:14,575 - wechat_app - ERROR - An exception happened, details: 'result' object has no attribute 'id'
2018-06-14 17:53:04,709 - wechat_app - ERROR - An exception happened, details: 'result' object has no attribute 'id'
2018-06-14 17:54:56,325 - wechat_app - ERROR - An exception happened, details: 'result' object has no attribute 'id'
2018-06-15 10:39:18,312 - wechat_app - ERROR - An exception happened, details: 'Info' object has no attribute 'the_date'
2018-06-15 10:39:58,145 - wechat_app - ERROR - An exception happened, details: 'Info' object has no attribute 'the_date'
2018-06-15 10:40:48,292 - wechat_app - ERROR - An exception happened, details: 'Info' object has no attribute 'the_date'
2018-06-15 10:41:30,414 - wechat_app - ERROR - An exception happened, details: 'Info' object has no attribute 'the_date'
2018-06-15 10:41:57,342 - wechat_app - ERROR - An exception happened, details: 'Info' object has no attribute 'the_date'
2018-06-15 10:54:16,598 - wechat_app - ERROR - An exception happened, details: argument must be 9-item sequence, not datetime.datetime
2018-06-15 10:57:54,845 - wechat_app - ERROR - An exception happened, details: argument must be 9-item sequence, not datetime.datetime
2018-06-15 11:12:32,855 - wechat_app - ERROR - An exception happened, details: 'Info' object has no attribute 'Info'
2018-06-15 11:21:04,398 - wechat_app - ERROR - An exception happened, details: 'Info' object has no attribute 'Info'
2018-06-15 11:21:38,063 - wechat_app - ERROR - An exception happened, details: 'Info' object has no attribute 'Info'
2018-06-15 11:22:25,296 - wechat_app - ERROR - An exception happened, details: 'Info' object has no attribute 'Info'
2018-06-15 14:43:44,259 - wechat_app - ERROR - An exception happened, details: 'result' object has no attribute 'start_time'
2018-06-15 14:45:20,015 - wechat_app - ERROR - An exception happened, details: 'result' object has no attribute 'start_time'
2018-06-15 14:47:01,618 - wechat_app - ERROR - An exception happened, details: can't compare datetime.timedelta to int
2018-06-16 16:19:47,607 - wechat_app - ERROR - An exception happened, details: (_mysql_exceptions.OperationalError) (2003, "Can't connect to MySQL server on '124.251.25.44' (10060)")
2018-06-16 16:25:28,559 - wechat_app - ERROR - An exception happened, details: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'mingrui'@'114.253.207.119' (using password: YES)")
2018-06-16 17:36:51,894 - wechat_app - ERROR - An exception happened, details: (_mysql_exceptions.OperationalError) (2006, 'MySQL server has gone away')
2018-06-16 17:40:46,265 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 17:40:55,589 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 17:41:04,665 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 17:41:11,765 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 17:53:42,006 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 17:54:31,256 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 17:54:36,178 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 17:54:49,483 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 17:56:55,842 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:01:37,187 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:06:04,138 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:06:57,019 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:08:56,904 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:13:47,494 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:14:27,611 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:16:39,134 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:16:40,907 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:16:51,499 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:17:29,038 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:17:35,161 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:20:26,596 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:21:28,693 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:21:45,746 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:22:00,283 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:22:41,154 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:23:37,910 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:26:54,674 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:26:59,094 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:27:20,782 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:27:39,799 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:27:51,176 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:28:07,828 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:28:28,342 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:29:06,085 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:29:16,194 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:29:57,644 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:30:26,825 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:30:43,910 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:30:51,599 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:33:39,733 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:42:35,798 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:42:48,249 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:42:53,670 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:43:15,762 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:43:56,601 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:45:54,053 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:46:25,911 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:53:34,604 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:53:53,053 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:54:01,354 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:55:25,813 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:55:36,612 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:56:12,713 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:57:03,509 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 18:57:33,217 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 19:00:40,145 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 19:16:08,082 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 19:17:56,210 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 19:18:50,934 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 19:19:11,951 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-16 21:41:41,990 - wechat_app - ERROR - An exception happened, details: commit() takes exactly 1 argument (2 given)
2018-06-16 21:41:41,990 - wechat_app - ERROR - An exception happened, details: commit() takes exactly 1 argument (2 given)
2018-06-16 22:07:02,650 - wechat_app - ERROR - An exception happened when 'is_exists' function executed, details: 'NoneType' object has no attribute 'open_id'
2018-06-16 22:07:02,650 - wechat_app - ERROR - An exception happened when 'is_exists' function executed, details: 'NoneType' object has no attribute 'open_id'
2018-06-17 14:37:10,723 - wechat_app - ERROR - An exception happened, details: (_mysql_exceptions.OperationalError) (2006, 'MySQL server has gone away')
2018-06-17 14:37:10,723 - wechat_app - ERROR - An exception happened, details: (_mysql_exceptions.OperationalError) (2006, 'MySQL server has gone away')
2018-06-17 14:37:37,204 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:37:37,204 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:38:02,665 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:38:02,665 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:39:16,401 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:39:16,401 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:40:17,154 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:40:17,154 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:40:35,046 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:40:35,046 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:40:49,000 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:40:49,000 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:41:19,364 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:41:19,364 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:41:36,492 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:41:36,492 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:44:43,809 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:44:43,809 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:45:08,861 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:45:08,861 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:45:27,184 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:45:27,184 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:45:47,164 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:45:47,164 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:48:33,395 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:48:33,395 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:49:32,020 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:49:32,020 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:50:07,130 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:50:07,130 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:52:38,283 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:52:38,283 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:52:41,963 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:52:41,963 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:53:52,957 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:53:52,957 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:55:02,562 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:55:02,562 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:55:39,296 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:55:39,296 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:56:22,617 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:56:22,617 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:56:33,232 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:56:33,232 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:56:37,907 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 14:56:37,907 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:00:04,720 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:00:04,720 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:00:59,434 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:00:59,434 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:01:14,203 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:01:14,203 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:02:31,631 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:02:31,631 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:02:50,680 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:02:50,680 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:03:57,628 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:03:57,628 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:05:12,082 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:05:12,082 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:06:42,532 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:06:42,532 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:06:57,331 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:06:57,331 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:07:06,963 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:07:06,963 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:08:13,938 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:08:13,938 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:11:48,823 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:11:48,823 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:15:55,203 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:15:55,203 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:16:54,460 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:16:54,460 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:19:07,841 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:19:07,841 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:19:37,148 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:19:37,148 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:19:49,875 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:19:49,875 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:20:34,726 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:20:34,726 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:27:16,548 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:27:16,548 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:27:51,384 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:27:51,384 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:27:58,181 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:27:58,181 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:28:34,882 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:28:34,882 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:33:14,301 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:33:14,301 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:34:45,181 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:34:45,181 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:35:09,772 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:35:09,772 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:35:36,822 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:35:36,822 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:36:04,961 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:36:04,961 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:36:49,660 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:36:49,660 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:37:34,411 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:37:34,411 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:38:03,346 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:38:03,346 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:38:15,786 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:38:15,786 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:38:32,309 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:38:32,309 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:38:47,325 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:38:47,325 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:39:06,861 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:39:06,861 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:39:19,431 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:39:19,431 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:41:32,019 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:41:32,019 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:42:12,602 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:42:12,602 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:42:24,565 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:42:24,565 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:42:59,325 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:42:59,325 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:43:04,760 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:43:04,760 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:43:30,664 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:43:30,664 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:43:33,463 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:43:33,463 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:43:54,171 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:43:54,171 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:43:58,845 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:43:58,845 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:44:38,372 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:44:38,372 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:45:27,197 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:45:27,197 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:45:52,115 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:45:52,115 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:46:15,651 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:46:15,651 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:46:30,305 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:46:30,305 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:46:45,200 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:46:45,200 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:46:50,848 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:46:50,848 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:47:03,607 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:47:03,607 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:47:20,157 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:47:20,157 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:48:32,538 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:48:32,538 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:52:38,463 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:52:38,463 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:53:01,967 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:53:01,967 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:53:23,884 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:53:23,884 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:54:24,072 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:54:24,072 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:55:05,371 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:55:05,371 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:57:20,503 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:57:20,503 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:57:55,973 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 15:57:55,973 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 16:07:02,571 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 16:07:02,571 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 16:07:45,105 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 16:07:45,105 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 16:08:12,480 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 16:08:12,480 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 16:08:52,749 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 16:08:52,749 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 16:09:54,578 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 16:09:54,578 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 16:10:18,861 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 16:10:18,861 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 16:11:00,742 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 16:11:00,742 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 16:11:23,256 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 16:11:23,256 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 16:11:48,101 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 16:11:48,101 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 16:13:17,763 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 16:13:17,763 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 16:13:46,164 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 16:13:46,164 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 16:14:18,413 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 16:14:18,413 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 16:14:23,904 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 16:14:23,904 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 16:16:16,348 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 16:16:16,348 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 16:37:25,301 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 16:37:25,301 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 16:40:16,493 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 16:40:16,493 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 16:40:50,230 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 16:40:50,230 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 16:41:11,020 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 16:41:11,020 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 17:26:25,595 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'")
2018-06-17 17:26:25,595 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'")
2018-06-17 17:27:17,836 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'")
2018-06-17 17:27:17,836 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'")
2018-06-17 17:27:40,112 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, None, None, None, None, None, None, '2018-06-17 17:27:16', None, None)]
2018-06-17 17:27:40,112 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, None, None, None, None, None, None, '2018-06-17 17:27:16', None, None)]
2018-06-17 17:41:21,349 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'")
2018-06-17 17:41:21,349 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'")
2018-06-17 17:41:21,365 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:41:21,365 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:41:24,351 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:41:24,351 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:41:24,355 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:41:24,355 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:41:24,359 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:41:24,359 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:41:24,759 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:41:24,759 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:41:47,864 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:41:47,864 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:42:36,665 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:42:36,665 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:42:41,056 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:42:41,056 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:43:06,661 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:43:06,661 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:45:50,035 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:45:50,035 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:45:50,046 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:45:50,046 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:46:04,559 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:46:04,559 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:48:49,996 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:48:49,996 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:52:47,318 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:52:47,318 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:54:35,838 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:54:35,838 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:54:35,854 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:54:35,854 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:54:49,467 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:54:49,467 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:55:37,012 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:55:37,012 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:55:53,823 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:55:53,823 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:57:08,714 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:57:08,714 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:57:08,726 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:57:08,726 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:57:31,197 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:57:31,197 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:59:42,512 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 17:59:42,512 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 18:02:15,000 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 18:02:15,000 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 18:03:28,509 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 18:03:28,509 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 18:04:44,844 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 18:04:44,844 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'content' in 'field list'") [SQL: u'INSERT INTO info (content, start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, u'undefined', u'undefined', u'undefined', u'undefined', u'undefined', None, '2018-06-17 17:41:20', None, u'')]
2018-06-17 18:05:53,108 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: (_mysql_exceptions.OperationalError) (1048, "Column 'is_available' cannot be null")
2018-06-17 18:05:53,108 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: (_mysql_exceptions.OperationalError) (1048, "Column 'is_available' cannot be null")
2018-06-17 18:08:20,683 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: (_mysql_exceptions.OperationalError) (1366, "Incorrect integer value: '' for column 'my_user_id' at row 1")
2018-06-17 18:08:20,683 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: (_mysql_exceptions.OperationalError) (1366, "Incorrect integer value: '' for column 'my_user_id' at row 1")
2018-06-17 18:08:49,598 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1366, "Incorrect integer value: '' for column 'my_user_id' at row 1") [SQL: u'INSERT INTO info (start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (u'2018-06-17 18:03', u'\u5317\u4eac\u5357\u7ad9', u'\u7fdf\u5bb6', u'\u8f66\u627e\u4eba', u'\u5168\u7a0b\u9ad8\u901f', 1, '2018-06-17 18:07:53', 0, u'')]
2018-06-17 18:08:49,598 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1366, "Incorrect integer value: '' for column 'my_user_id' at row 1") [SQL: u'INSERT INTO info (start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (u'2018-06-17 18:03', u'\u5317\u4eac\u5357\u7ad9', u'\u7fdf\u5bb6', u'\u8f66\u627e\u4eba', u'\u5168\u7a0b\u9ad8\u901f', 1, '2018-06-17 18:07:53', 0, u'')]
2018-06-17 18:10:51,585 - wechat_app - ERROR - An exception happened, details: 'Info' object has no attribute 'content'
2018-06-17 18:10:51,585 - wechat_app - ERROR - An exception happened, details: 'Info' object has no attribute 'content'
2018-06-17 18:11:37,625 - wechat_app - ERROR - An exception happened, details: 'Info' object has no attribute 'content'
2018-06-17 18:11:37,625 - wechat_app - ERROR - An exception happened, details: 'Info' object has no attribute 'content'
2018-06-17 18:12:33,842 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: (_mysql_exceptions.OperationalError) (1366, "Incorrect integer value: '' for column 'my_user_id' at row 1")
2018-06-17 18:12:33,842 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: (_mysql_exceptions.OperationalError) (1366, "Incorrect integer value: '' for column 'my_user_id' at row 1")
2018-06-17 18:13:02,628 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1366, "Incorrect integer value: '' for column 'my_user_id' at row 1") [SQL: u'INSERT INTO info (start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (u'2018-06-17 18:11', u'\u5317\u4eac\u5357\u4e09\u73af', u'\u7fdf\u5bb6', u'\u8f66\u627e\u4eba', u'\u901f\u5ea6\u53d1\u987a\u4e30', 1, '2018-06-17 18:12:33', 0, u'')]
2018-06-17 18:13:02,628 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1366, "Incorrect integer value: '' for column 'my_user_id' at row 1") [SQL: u'INSERT INTO info (start_time, start_position, end_position, type, remark, is_available, add_time, browse, my_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (u'2018-06-17 18:11', u'\u5317\u4eac\u5357\u4e09\u73af', u'\u7fdf\u5bb6', u'\u8f66\u627e\u4eba', u'\u901f\u5ea6\u53d1\u987a\u4e30', 1, '2018-06-17 18:12:33', 0, u'')]
2018-06-17 19:10:21,170 - wechat_app - ERROR - An exception happened, details: 'Info' object has no attribute 'content'
2018-06-17 19:10:21,170 - wechat_app - ERROR - An exception happened, details: 'Info' object has no attribute 'content'
2018-06-17 19:13:35,219 - wechat_app - ERROR - An exception happened, details: 'Info' object has no attribute 'content'
2018-06-17 19:13:35,219 - wechat_app - ERROR - An exception happened, details: 'Info' object has no attribute 'content'
2018-06-17 19:14:40,869 - wechat_app - ERROR - An exception happened, details: 'Info' object has no attribute 'content'
2018-06-17 19:14:40,869 - wechat_app - ERROR - An exception happened, details: 'Info' object has no attribute 'content'
2018-06-17 19:19:37,098 - wechat_app - ERROR - An exception happened, details: 'Info' object has no attribute 'content'
2018-06-17 19:19:37,098 - wechat_app - ERROR - An exception happened, details: 'Info' object has no attribute 'content'
2018-06-17 19:23:21,155 - wechat_app - ERROR - An exception happened, details: 'Info' object has no attribute 'content'
2018-06-17 19:23:21,155 - wechat_app - ERROR - An exception happened, details: 'Info' object has no attribute 'content'
2018-06-17 19:23:46,865 - wechat_app - ERROR - An exception happened, details: 'Info' object has no attribute 'content'
2018-06-17 19:23:46,865 - wechat_app - ERROR - An exception happened, details: 'Info' object has no attribute 'content'
2018-06-17 19:26:18,663 - wechat_app - ERROR - An exception happened, details: 'Info' object has no attribute 'content'
2018-06-17 19:26:18,663 - wechat_app - ERROR - An exception happened, details: 'Info' object has no attribute 'content'
2018-06-17 19:27:00,280 - wechat_app - ERROR - An exception happened, details: 'Info' object has no attribute 'content'
2018-06-17 19:27:00,280 - wechat_app - ERROR - An exception happened, details: 'Info' object has no attribute 'content'
2018-06-17 19:29:21,094 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: (_mysql_exceptions.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`wechat_app`.`info`, CONSTRAINT `fk_info_user` FOREIGN KEY (`open_id`) REFERENCES `my_user` (`open_id`))')
2018-06-17 19:29:21,094 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: (_mysql_exceptions.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`wechat_app`.`info`, CONSTRAINT `fk_info_user` FOREIGN KEY (`open_id`) REFERENCES `my_user` (`open_id`))')
2018-06-17 19:29:21,108 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`wechat_app`.`info`, CONSTRAINT `fk_info_user` FOREIGN KEY (`open_id`) REFERENCES `my_user` (`open_id`))') [SQL: u'INSERT INTO info (start_time, start_position, end_position, type, remark, is_available, add_time, browse, open_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (u'2018-06-17 19:27', u'\u5317\u4eac\u5357\u7ad9', u'\u4e34\u9091\u7fdf\u5bb6\u9547', u'\u8f66\u627e\u4eba', u'\u53ef\u4e58\u57503\u4eba', 1, '2018-06-17 19:29:20', 0, u'')]
2018-06-17 19:29:21,108 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`wechat_app`.`info`, CONSTRAINT `fk_info_user` FOREIGN KEY (`open_id`) REFERENCES `my_user` (`open_id`))') [SQL: u'INSERT INTO info (start_time, start_position, end_position, type, remark, is_available, add_time, browse, open_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (u'2018-06-17 19:27', u'\u5317\u4eac\u5357\u7ad9', u'\u4e34\u9091\u7fdf\u5bb6\u9547', u'\u8f66\u627e\u4eba', u'\u53ef\u4e58\u57503\u4eba', 1, '2018-06-17 19:29:20', 0, u'')]
2018-06-17 19:29:21,115 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`wechat_app`.`info`, CONSTRAINT `fk_info_user` FOREIGN KEY (`open_id`) REFERENCES `my_user` (`open_id`))') [SQL: u'INSERT INTO info (start_time, start_position, end_position, type, remark, is_available, add_time, browse, open_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (u'2018-06-17 19:27', u'\u5317\u4eac\u5357\u7ad9', u'\u4e34\u9091\u7fdf\u5bb6\u9547', u'\u8f66\u627e\u4eba', u'\u53ef\u4e58\u57503\u4eba', 1, '2018-06-17 19:29:20', 0, u'')]
2018-06-17 19:29:21,115 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`wechat_app`.`info`, CONSTRAINT `fk_info_user` FOREIGN KEY (`open_id`) REFERENCES `my_user` (`open_id`))') [SQL: u'INSERT INTO info (start_time, start_position, end_position, type, remark, is_available, add_time, browse, open_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (u'2018-06-17 19:27', u'\u5317\u4eac\u5357\u7ad9', u'\u4e34\u9091\u7fdf\u5bb6\u9547', u'\u8f66\u627e\u4eba', u'\u53ef\u4e58\u57503\u4eba', 1, '2018-06-17 19:29:20', 0, u'')]
2018-06-17 19:29:36,538 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`wechat_app`.`info`, CONSTRAINT `fk_info_user` FOREIGN KEY (`open_id`) REFERENCES `my_user` (`open_id`))') [SQL: u'INSERT INTO info (start_time, start_position, end_position, type, remark, is_available, add_time, browse, open_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (u'2018-06-17 19:27', u'\u5317\u4eac\u5357\u7ad9', u'\u4e34\u9091\u7fdf\u5bb6\u9547', u'\u8f66\u627e\u4eba', u'\u53ef\u4e58\u57503\u4eba', 1, '2018-06-17 19:29:20', 0, u'')]
2018-06-17 19:29:36,538 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`wechat_app`.`info`, CONSTRAINT `fk_info_user` FOREIGN KEY (`open_id`) REFERENCES `my_user` (`open_id`))') [SQL: u'INSERT INTO info (start_time, start_position, end_position, type, remark, is_available, add_time, browse, open_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (u'2018-06-17 19:27', u'\u5317\u4eac\u5357\u7ad9', u'\u4e34\u9091\u7fdf\u5bb6\u9547', u'\u8f66\u627e\u4eba', u'\u53ef\u4e58\u57503\u4eba', 1, '2018-06-17 19:29:20', 0, u'')]
2018-06-17 19:32:40,444 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`wechat_app`.`info`, CONSTRAINT `fk_info_user` FOREIGN KEY (`open_id`) REFERENCES `my_user` (`open_id`))') [SQL: u'INSERT INTO info (start_time, start_position, end_position, type, remark, is_available, add_time, browse, open_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (u'2018-06-17 19:27', u'\u5317\u4eac\u5357\u7ad9', u'\u4e34\u9091\u7fdf\u5bb6\u9547', u'\u8f66\u627e\u4eba', u'\u53ef\u4e58\u57503\u4eba', 1, '2018-06-17 19:29:20', 0, u'')]
2018-06-17 19:32:40,444 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`wechat_app`.`info`, CONSTRAINT `fk_info_user` FOREIGN KEY (`open_id`) REFERENCES `my_user` (`open_id`))') [SQL: u'INSERT INTO info (start_time, start_position, end_position, type, remark, is_available, add_time, browse, open_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (u'2018-06-17 19:27', u'\u5317\u4eac\u5357\u7ad9', u'\u4e34\u9091\u7fdf\u5bb6\u9547', u'\u8f66\u627e\u4eba', u'\u53ef\u4e58\u57503\u4eba', 1, '2018-06-17 19:29:20', 0, u'')]
2018-06-17 19:36:59,072 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`wechat_app`.`info`, CONSTRAINT `fk_info_user` FOREIGN KEY (`open_id`) REFERENCES `my_user` (`open_id`))') [SQL: u'INSERT INTO info (start_time, start_position, end_position, type, remark, is_available, add_time, browse, open_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (u'2018-06-17 19:27', u'\u5317\u4eac\u5357\u7ad9', u'\u4e34\u9091\u7fdf\u5bb6\u9547', u'\u8f66\u627e\u4eba', u'\u53ef\u4e58\u57503\u4eba', 1, '2018-06-17 19:29:20', 0, u'')]
2018-06-17 19:36:59,072 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`wechat_app`.`info`, CONSTRAINT `fk_info_user` FOREIGN KEY (`open_id`) REFERENCES `my_user` (`open_id`))') [SQL: u'INSERT INTO info (start_time, start_position, end_position, type, remark, is_available, add_time, browse, open_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (u'2018-06-17 19:27', u'\u5317\u4eac\u5357\u7ad9', u'\u4e34\u9091\u7fdf\u5bb6\u9547', u'\u8f66\u627e\u4eba', u'\u53ef\u4e58\u57503\u4eba', 1, '2018-06-17 19:29:20', 0, u'')]
2018-06-17 19:43:55,049 - wechat_app - ERROR - An exception happened, details: 'Info' object has no attribute 'content'
2018-06-17 19:43:55,049 - wechat_app - ERROR - An exception happened, details: 'Info' object has no attribute 'content'
2018-06-17 19:44:20,625 - wechat_app - ERROR - An exception happened, details: 'Info' object has no attribute 'content'
2018-06-17 19:44:20,625 - wechat_app - ERROR - An exception happened, details: 'Info' object has no attribute 'content'
2018-06-17 19:45:17,109 - wechat_app - ERROR - An exception happened, details: 'Info' object has no attribute 'content'
2018-06-17 19:45:17,109 - wechat_app - ERROR - An exception happened, details: 'Info' object has no attribute 'content'
2018-06-17 20:47:58,622 - wechat_app - ERROR - An exception happened, details: (_mysql_exceptions.OperationalError) (2013, 'Lost connection to MySQL server during query')
2018-06-17 20:47:58,622 - wechat_app - ERROR - An exception happened, details: (_mysql_exceptions.OperationalError) (2013, 'Lost connection to MySQL server during query')
2018-06-17 20:47:58,640 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 20:47:58,640 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 20:48:19,779 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 20:48:19,779 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 21:49:28,759 - wechat_app - ERROR - An exception happened, details: (_mysql_exceptions.OperationalError) (2013, 'Lost connection to MySQL server during query')
2018-06-17 21:49:28,759 - wechat_app - ERROR - An exception happened, details: (_mysql_exceptions.OperationalError) (2013, 'Lost connection to MySQL server during query')
2018-06-17 21:50:02,470 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 21:50:02,470 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 21:54:39,403 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 21:54:39,403 - wechat_app - ERROR - An exception happened, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 21:54:51,345 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 21:54:51,345 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back
2018-06-17 21:57:06,645 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: u'INSERT INTO info (start_time, start_position, end_position, type, remark, is_available, add_time, browse, open_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: [{'remark': u'', 'open_id': u'oSSj64n0tZNJAxm8utxFB7pbwk-Q', 'browse': 0, 'start_time': u'2018-06-17 21:54', 'end_position': u'', 'start_position': u'', 'is_available': 1, 'type': u'\u4eba\u627e\u8f66', 'add_time': '2018-06-17 21:54:51'}]]
2018-06-17 21:57:06,645 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: u'INSERT INTO info (start_time, start_position, end_position, type, remark, is_available, add_time, browse, open_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: [{'remark': u'', 'open_id': u'oSSj64n0tZNJAxm8utxFB7pbwk-Q', 'browse': 0, 'start_time': u'2018-06-17 21:54', 'end_position': u'', 'start_position': u'', 'is_available': 1, 'type': u'\u4eba\u627e\u8f66', 'add_time': '2018-06-17 21:54:51'}]]
2018-06-17 21:57:44,617 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: u'INSERT INTO info (start_time, start_position, end_position, type, remark, is_available, add_time, browse, open_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: [{'remark': u'', 'open_id': u'oSSj64n0tZNJAxm8utxFB7pbwk-Q', 'browse': 0, 'start_time': u'2018-06-17 21:54', 'end_position': u'', 'start_position': u'', 'is_available': 1, 'type': u'\u4eba\u627e\u8f66', 'add_time': '2018-06-17 21:54:51'}]]
2018-06-17 21:57:44,617 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: u'INSERT INTO info (start_time, start_position, end_position, type, remark, is_available, add_time, browse, open_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: [{'remark': u'', 'open_id': u'oSSj64n0tZNJAxm8utxFB7pbwk-Q', 'browse': 0, 'start_time': u'2018-06-17 21:54', 'end_position': u'', 'start_position': u'', 'is_available': 1, 'type': u'\u4eba\u627e\u8f66', 'add_time': '2018-06-17 21:54:51'}]]
2018-06-17 21:58:30,500 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: u'INSERT INTO info (start_time, start_position, end_position, type, remark, is_available, add_time, browse, open_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: [{'remark': u'', 'open_id': u'oSSj64n0tZNJAxm8utxFB7pbwk-Q', 'browse': 0, 'start_time': u'2018-06-17 21:54', 'end_position': u'', 'start_position': u'', 'is_available': 1, 'type': u'\u4eba\u627e\u8f66', 'add_time': '2018-06-17 21:54:51'}]]
2018-06-17 21:58:30,500 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: u'INSERT INTO info (start_time, start_position, end_position, type, remark, is_available, add_time, browse, open_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: [{'remark': u'', 'open_id': u'oSSj64n0tZNJAxm8utxFB7pbwk-Q', 'browse': 0, 'start_time': u'2018-06-17 21:54', 'end_position': u'', 'start_position': u'', 'is_available': 1, 'type': u'\u4eba\u627e\u8f66', 'add_time': '2018-06-17 21:54:51'}]]
2018-06-17 21:58:45,907 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: u'INSERT INTO info (start_time, start_position, end_position, type, remark, is_available, add_time, browse, open_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: [{'remark': u'', 'open_id': u'oSSj64n0tZNJAxm8utxFB7pbwk-Q', 'browse': 0, 'start_time': u'2018-06-17 21:54', 'end_position': u'', 'start_position': u'', 'is_available': 1, 'type': u'\u4eba\u627e\u8f66', 'add_time': '2018-06-17 21:54:51'}]]
2018-06-17 21:58:45,907 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: u'INSERT INTO info (start_time, start_position, end_position, type, remark, is_available, add_time, browse, open_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: [{'remark': u'', 'open_id': u'oSSj64n0tZNJAxm8utxFB7pbwk-Q', 'browse': 0, 'start_time': u'2018-06-17 21:54', 'end_position': u'', 'start_position': u'', 'is_available': 1, 'type': u'\u4eba\u627e\u8f66', 'add_time': '2018-06-17 21:54:51'}]]
2018-06-17 21:59:26,894 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: u'INSERT INTO info (start_time, start_position, end_position, type, remark, is_available, add_time, browse, open_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: [{'remark': u'', 'open_id': u'oSSj64n0tZNJAxm8utxFB7pbwk-Q', 'browse': 0, 'start_time': u'2018-06-17 21:54', 'end_position': u'', 'start_position': u'', 'is_available': 1, 'type': u'\u4eba\u627e\u8f66', 'add_time': '2018-06-17 21:54:51'}]]
2018-06-17 21:59:26,894 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: u'INSERT INTO info (start_time, start_position, end_position, type, remark, is_available, add_time, browse, open_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: [{'remark': u'', 'open_id': u'oSSj64n0tZNJAxm8utxFB7pbwk-Q', 'browse': 0, 'start_time': u'2018-06-17 21:54', 'end_position': u'', 'start_position': u'', 'is_available': 1, 'type': u'\u4eba\u627e\u8f66', 'add_time': '2018-06-17 21:54:51'}]]
2018-06-17 21:59:52,701 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: u'INSERT INTO info (start_time, start_position, end_position, type, remark, is_available, add_time, browse, open_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: [{'remark': u'', 'open_id': u'oSSj64n0tZNJAxm8utxFB7pbwk-Q', 'browse': 0, 'start_time': u'2018-06-17 21:54', 'end_position': u'', 'start_position': u'', 'is_available': 1, 'type': u'\u4eba\u627e\u8f66', 'add_time': '2018-06-17 21:54:51'}]]
2018-06-17 21:59:52,701 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: u'INSERT INTO info (start_time, start_position, end_position, type, remark, is_available, add_time, browse, open_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: [{'remark': u'', 'open_id': u'oSSj64n0tZNJAxm8utxFB7pbwk-Q', 'browse': 0, 'start_time': u'2018-06-17 21:54', 'end_position': u'', 'start_position': u'', 'is_available': 1, 'type': u'\u4eba\u627e\u8f66', 'add_time': '2018-06-17 21:54:51'}]]
2018-06-17 22:01:38,538 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: u'INSERT INTO info (start_time, start_position, end_position, type, remark, is_available, add_time, browse, open_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: [{'remark': u'', 'open_id': u'oSSj64n0tZNJAxm8utxFB7pbwk-Q', 'browse': 0, 'start_time': u'2018-06-17 21:54', 'end_position': u'', 'start_position': u'', 'is_available': 1, 'type': u'\u4eba\u627e\u8f66', 'add_time': '2018-06-17 21:54:51'}]]
2018-06-17 22:01:38,538 - wechat_app - ERROR - An exception happened, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: u'INSERT INTO info (start_time, start_position, end_position, type, remark, is_available, add_time, browse, open_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: [{'remark': u'', 'open_id': u'oSSj64n0tZNJAxm8utxFB7pbwk-Q', 'browse': 0, 'start_time': u'2018-06-17 21:54', 'end_position': u'', 'start_position': u'', 'is_available': 1, 'type': u'\u4eba\u627e\u8f66', 'add_time': '2018-06-17 21:54:51'}]]
2018-06-17 22:03:13,551 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: u'INSERT INTO info (start_time, start_position, end_position, type, remark, is_available, add_time, browse, open_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: [{'remark': u'', 'open_id': u'oSSj64n0tZNJAxm8utxFB7pbwk-Q', 'browse': 0, 'start_time': u'2018-06-17 21:54', 'end_position': u'', 'start_position': u'', 'is_available': 1, 'type': u'\u4eba\u627e\u8f66', 'add_time': '2018-06-17 21:54:51'}]]
2018-06-17 22:03:13,551 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: u'INSERT INTO info (start_time, start_position, end_position, type, remark, is_available, add_time, browse, open_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: [{'remark': u'', 'open_id': u'oSSj64n0tZNJAxm8utxFB7pbwk-Q', 'browse': 0, 'start_time': u'2018-06-17 21:54', 'end_position': u'', 'start_position': u'', 'is_available': 1, 'type': u'\u4eba\u627e\u8f66', 'add_time': '2018-06-17 21:54:51'}]]
2018-06-17 22:04:12,891 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: u'INSERT INTO info (start_time, start_position, end_position, type, remark, is_available, add_time, browse, open_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: [{'remark': u'', 'open_id': u'oSSj64n0tZNJAxm8utxFB7pbwk-Q', 'browse': 0, 'start_time': u'2018-06-17 21:54', 'end_position': u'', 'start_position': u'', 'is_available': 1, 'type': u'\u4eba\u627e\u8f66', 'add_time': '2018-06-17 21:54:51'}]]
2018-06-17 22:04:12,891 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: u'INSERT INTO info (start_time, start_position, end_position, type, remark, is_available, add_time, browse, open_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: [{'remark': u'', 'open_id': u'oSSj64n0tZNJAxm8utxFB7pbwk-Q', 'browse': 0, 'start_time': u'2018-06-17 21:54', 'end_position': u'', 'start_position': u'', 'is_available': 1, 'type': u'\u4eba\u627e\u8f66', 'add_time': '2018-06-17 21:54:51'}]]
2018-06-18 14:23:29,542 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: (_mysql_exceptions.OperationalError) (1048, "Column 'phone' cannot be null")
2018-06-18 14:23:29,542 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: (_mysql_exceptions.OperationalError) (1048, "Column 'phone' cannot be null")
2018-06-18 14:23:57,713 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1048, "Column 'phone' cannot be null") [SQL: u'INSERT INTO info (start_time, start_position, end_position, type, remark, is_available, add_time, browse, phone, open_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (u'2018-06-18 18:22', u'\u4e34\u9091\u6c7d\u8f66\u603b\u7ad9', u'\u5317\u4eac\u5357\u4e09\u73af\u77f3\u69b4\u5e84', u'\u4eba\u627e\u8f66', u'3\u4e2a\u4eba\uff0c\u67092\u4e2a\u884c\u674e\u7bb1\uff0c\u6700\u597d\u662f\u6709\u7a7a\u8c03', 1, '2018-06-18 14:23:29', 0, None, u'oSSj64n0tZNJAxm8utxFB7pbwk-Q')]
2018-06-18 14:23:57,713 - wechat_app - ERROR - An exception happened when insert a 'info' entity into DB, details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1048, "Column 'phone' cannot be null") [SQL: u'INSERT INTO info (start_time, start_position, end_position, type, remark, is_available, add_time, browse, phone, open_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (u'2018-06-18 18:22', u'\u4e34\u9091\u6c7d\u8f66\u603b\u7ad9', u'\u5317\u4eac\u5357\u4e09\u73af\u77f3\u69b4\u5e84', u'\u4eba\u627e\u8f66', u'3\u4e2a\u4eba\uff0c\u67092\u4e2a\u884c\u674e\u7bb1\uff0c\u6700\u597d\u662f\u6709\u7a7a\u8c03', 1, '2018-06-18 14:23:29', 0, None, u'oSSj64n0tZNJAxm8utxFB7pbwk-Q')]
2018-06-18 16:15:17,309 - wechat_app - ERROR - An exception happened when get a 'info' entity from DB, details: 'result' object has no attribute 'browse'
2018-06-18 16:15:17,309 - wechat_app - ERROR - An exception happened when get a 'info' entity from DB, details: 'result' object has no attribute 'browse'
2018-06-18 16:15:44,828 - wechat_app - ERROR - An exception happened when get a 'info' entity from DB, details: 'result' object has no attribute 'browse'
2018-06-18 16:15:44,828 - wechat_app - ERROR - An exception happened when get a 'info' entity from DB, details: 'result' object has no attribute 'browse'
2018-06-18 16:16:15,543 - wechat_app - ERROR - An exception happened when get a 'info' entity from DB, details: 'result' object has no attribute 'browse'
2018-06-18 16:16:15,543 - wechat_app - ERROR - An exception happened when get a 'info' entity from DB, details: 'result' object has no attribute 'browse'
2018-06-18 16:18:06,404 - wechat_app - ERROR - An exception happened when get a 'info' entity from DB, details: 'result' object has no attribute 'browse'
2018-06-18 16:18:06,404 - wechat_app - ERROR - An exception happened when get a 'info' entity from DB, details: 'result' object has no attribute 'browse'
2018-06-18 16:20:53,428 - wechat_app - ERROR - An exception happened when get a 'info' entity from DB, details: 'result' object has no attribute 'browse'
2018-06-18 16:20:53,428 - wechat_app - ERROR - An exception happened when get a 'info' entity from DB, details: 'result' object has no attribute 'browse'
2018-06-18 16:21:41,805 - wechat_app - ERROR - An exception happened when get a 'info' entity from DB, details: Class 'sqlalchemy.util._collections.result' is not mapped
2018-06-18 16:21:41,805 - wechat_app - ERROR - An exception happened when get a 'info' entity from DB, details: Class 'sqlalchemy.util._collections.result' is not mapped
2018-06-18 19:53:40,581 - wechat_app - ERROR - An exception happened, details: (_mysql_exceptions.OperationalError) (2003, "Can't connect to MySQL server on '118.24.121.119' (10060)")
2018-06-18 19:53:40,581 - wechat_app - ERROR - An exception happened, details: (_mysql_exceptions.OperationalError) (2003, "Can't connect to MySQL server on '118.24.121.119' (10060)")
2018-06-18 19:54:33,428 - wechat_app - ERROR - An exception happened, details: (_mysql_exceptions.OperationalError) (2003, "Can't connect to MySQL server on '118.24.121.119' (10060)")
2018-06-18 19:54:33,428 - wechat_app - ERROR - An exception happened, details: (_mysql_exceptions.OperationalError) (2003, "Can't connect to MySQL server on '118.24.121.119' (10060)")
2018-06-18 19:58:23,993 - wechat_app - ERROR - An exception happened, details: (_mysql_exceptions.OperationalError) (2003, "Can't connect to MySQL server on '118.24.121.119' (10060)")
2018-06-18 19:58:23,993 - wechat_app - ERROR - An exception happened, details: (_mysql_exceptions.OperationalError) (2003, "Can't connect to MySQL server on '118.24.121.119' (10060)")
